const SUPABASE_URL = 'https://tpllajxzsaczidyyiyuy.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwbGxhanh6c2FjemlkeXlpeXV5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0MDUzMjcsImV4cCI6MjA2MDk4MTMyN30.Jd14llB51tqaehj1XGzzHdJ0TwG8eNdXltV57QDxl8E';

export { SUPABASE_URL, SUPABASE_ANON_KEY };
